services:

  api1:
    container_name: api1
    hostname: api1
    build: .
    ports:
      - "8001:8001"
    env_file:
      - ".env.base"
      - ".env"
    environment:
      PORT: 8001

  api2:
    container_name: api2
    hostname: api2
    build: .
    ports:
      - "8002:8002"
    env_file:
      - ".env.base"
      - ".env"
    environment:
      PORT: 8002



#  jaeger:
#    container_name: jaeger
#    hostname: jaeger
#    image: jaegertracing/all-in-one
#    environment:
#      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
#    ports:
#      - "5775:5775/udp"
#      - "6831:6831/udp"
#      - "6832:6832/udp"
#      - "5778:5778"
#      - "16686:16686"
#      - "14268:14268"
#      - "9411:9411"
#      - "4317:4317"
#      - "4318:4318"

  collector:
    container_name: collector
    hostname: collector
    image: otel/opentelemetry-collector
    volumes:
      - ./collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
